Revert "video: msm: Unlock mutex before update notify"
  Looks like we need more previous patches:

drivers/video/msm/msm_fb.c:3563:20: error: 'struct msm_fb_data_type' has no member named 'entry_mutex'

This reverts commit 07df7b5c18df17d4b8dbb48f3150f7af1244c1b8.